// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: env("DATABASE_URL"),
    // Shadow database: Opsiyonel (sadece prisma migrate dev için gerekli)
    // prisma db push shadow DB kullanmaz, bu yüzden tanımlamaya gerek yok
    ...(process.env.SHADOW_DATABASE_URL && {
      shadowDatabaseUrl: env("SHADOW_DATABASE_URL"),
    }),
  },
  // Note: generator config (engineType: "library") is defined in schema.prisma
});
